- name: Configurazione limiti file aperti per un utente
  hosts: all
  become: true  # Esegui come root

  tasks:
    - name: Aggiungi limiti di file aperti al file limits.conf
      vars:
        ambiente: 'produzione'
        target_user: "" 
      template:
        src: templates/limits.conf.j2
        dest: /etc/security/limits.conf
        owner: root
        group: root
        mode: '0644'