# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  
  # Prima VM
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "Ubuntu/jammy64"
    vm1.vm.hostname = "vm1"

    # Impostazioni di rete e assegnazione IP
    vm1.vm.network "private_network", ip: "192.168.168.19"

    # Risorse VM
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end

    # Provision Ansible 
    config.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "1.8"
      ansible.playbook = "playbook2.yml"
    end
  end 
end
